spring:
  rabbitmq:
    host: 192.168.120.135
    port: 5672
    username: guest
    password: guest
zuul:
  routes:
    #  /myProduct/product/list -> /product/product/list
    product:
      path: /myProduct/**
      service-id: product
      # 获取cookie
      securityHeaders:

      # 简洁写法
#    product: /myProduct/**
  # 排除路径
  ignored-patterns:
    - /**/test
  #
  sensitive-headers:
