env: dev1
spring:
  rabbitmq:
    host: 192.168.120.135
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings: 
        myMessageInput:
          group: product
          content-type: application/json
